### ISSUE TITLE
Add borders and backgrounds to the flag elements

### ISSUE THREAD

**Issue by Lathrisk** [openownership/visualisation-tool#100]
https://docs.google.com/document/d/1KyZO8XaRGyAxAtKf0UhbBQuWM6DASb2l310h8J0ewRY/edit?disco=AAAAWjMYxjM

**Comment by Lathrisk** [comment]
I've added a border to the flags. As suspected, it creates a border around a rectangle that contains the Nepalese flag (as an example. This might be the exception as most flags are rectangular in some form.

Backgrounds are WIP

**Comment by kd-ods** [comment]
The drop shadows are cut off sometimes:

![image](https://user-images.githubusercontent.com/35495305/165759361-2ced880d-3c8e-4c9f-b367-a6dd95e878c3.png)

[Data here](https://drive.google.com/file/d/1NRvc9Beupb3Xggq8HA7_zrdWeHMOu3IG/view?usp=sharing).

**Comment by Lathrisk** [comment]
@kd-ods What browser was this? The sample data seems to work on in my machine in Chrome, but this could be a browser specific issue with drop shadows (which we can probably fix somehow)

**Comment by kd-ods** [comment]
@Lathrisk - ahhh. Interesting. So that image is from Firefox 99.0 (64-bit) on Ubuntu 18. And, indeed, it looks better on Chrome:

![image](https://user-images.githubusercontent.com/35495305/165762139-be389b35-6a53-4058-a0c5-bdb97601b67a.png)

Since Chrome has got over 75% browser market hare atm, it's less of an issue. 

Just logging here for future.

**Comment by Lathrisk** [comment]
@StephenAbbott @Blueskies00 @kd-ods @siwhitehouse @lgs85 

This update has now been merged, deployed, and published to NPM (v0.3.3).
This patch switches from `drop-shadow` on the SVG element to `stroke` on the embedded `rect` element. This means that the flags should have a border that is consistent across browsers and image editing software.

**Comment by StephenAbbott** [comment]
Thanks for sorting this, @Lathrisk. I've updated the [BODS data visualiser page](https://www.openownership.org/en/publications/beneficial-ownership-visualisation-system/bods-data-visualiser/) now too.
