### ISSUE TITLE
Unknown properties of interests should be well represented

### ISSUE THREAD

**Issue by kd-ods** [openownership/visualisation-tool#105]
In the data there are 3 things that can be unknown about an interest:

(1) Its directness
(2) Its type (shareholding, appointment of directors etc.)
(3) Its magnitude ('share').

(Or any combination of the above.)

So edges should not have the label 'unknown' since that is ambiguous. 

In the short term, the 'unknown' label should be replaced with: 'Interest details unknown' since it is displayed when the interests array is completely empty (and possibly in other cases?).

In the longer term, I suggest that unknown values in the above cases are represented as follows:

(1) An 'unknown' value for `directOrIndirect` is represented as a dotted line (as is an 'indirect' value)
(2) The title of the [interestType](https://github.com/openownership/data-standard/blob/master/schema/codelists/interestType.csv) is used as a label. And where no `interestType` is supplied 'empty interest' is used as the label.
(3) The default line weight is used where no magnitude (`share`) is given.

**Comment by StephenAbbott** [comment]
@Lathrisk Could you implement @kd-ods' suggested short-term solution as part of visualisation sprint 4 and then leave this card open for future reference?

**Comment by Lathrisk** [comment]
@StephenAbbott The short term solution has already been implemented to my knowledge - https://openownership.github.io/visualisation-tool/

**Comment by StephenAbbott** [comment]
@Lathrisk Ah OK. Couldn't tell from this issue cc @kd-ods

**Comment by Lathrisk** [comment]
WRT to the longer term solution:

> (1) An 'unknown' value for directOrIndirect is represented as a dotted line (as is an 'indirect' value)
> (2) The title of the [interestType](https://github.com/openownership/data-standard/blob/master/schema/codelists/interestType.csv) is used as a label. And where no interestType is supplied 'empty interest' is used as the label.
> (3) The default line weight is used where no magnitude (share) is given.

1) and 3) are already in effect
2) requires more investigation to decide how we map interestTypes to the visual language or represent them differently

@kd-ods also proposed no label on an edge where the interest type is within the [codelist](https://github.com/openownership/data-standard/blob/master/schema/codelists/interestType.csv), and stating 'Interest details unknown' when the data contains no indication of the interest types or values.

**Comment by Lathrisk** [comment]
@kd-ods Also for note, I have data from the register that contains `interestTypes` such as `other-influence-or-control-of-trust`. I'm excluding these for now, but this likely comes back to the question of how much backwards compatibility we want to support.

**Comment by Lathrisk** [comment]
@kd-ods @lgs85 My understanding is that it is possible for one `ownershipAndControlStatement` to have multiple `interestTypes` in the `share` array. I'm also going to assume that `unknownInterest` can occur in the same array as others (e.g. where 20% is known as control, but the other 80% is unknown). If that assumption is correct then we should only display "Interest details unknown" when `unknownInterest` is the only `interestType`. Does that make sense?

**Comment by Lathrisk** [comment]
@lgs85 thanks, and apologies, I meant the `interests` array, not the `share` array, but that makes sense. I'll check for instances when `unknownInterest` is the only `interestType`.

**Comment by kd-ods** [comment]
That all sounds good. 

> ... we should only display "Interest details unknown" when unknownInterest is the only interestType.

Plus when the `interests` array is empty or the property doesn't exist, right?
