### ISSUE TITLE
Visualising unknown persons: adopt the Cytoscape/Register approach

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/visualisation-tool#111]
For a recent presentation, I used the example of SQUARESTONE GROWTH LLP from the Open Ownership Register to showcase how some South African data on companies is captured from the disclosures in other jurisdictions:
https://register.openownership.org/entities/5b175cc59dfc3fae18cfd033

The [entity graph on the Register](https://register.openownership.org/entities/5b175cc59dfc3fae18cfd033/graph) represents the unknown UBOs as two separate unknown persons (see below):

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1506468/168998647-a0557fce-0a6a-41f6-a144-fbf2cbe2e98c.png">

Whereas the BODS Visualiser version links back to what looks like one individual although I realise that the label does say "Unknown person(s)" 
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/1506468/168999439-0966463c-f7d2-4ce9-a9db-6fd8236db9bc.png">

In terms of how easy it is to understand these diagrams, I wanted to record an issue here for us to discuss whether the Cytoscape or BODS Visualiser approach is the best/clearest for users to avoid potential assumptions (which can't be proven by the data) about whether or not it is the same unknown person at the end of the chain here.

**Comment by kd-ods** [comment]
@StephenAbbott - that's interesting.

I'm not sure the question should be: which "approach is the best/clearest for users". The data exported from the register links both Old Mutual Limit and Majik Property holdings to the same Unknown person, so my question is: why is the register telling one story visually and another in the data?

**Comment by kd-ods** [comment]
I take all that back!! In the data, a node is not created for an unknown person, there is simply a hanging edge.

So the question is, as you say @StephenAbbott: which "approach is the best/clearest for users"?

And the answer is certainly: the register approach. 

I'll edit the title of this issue to reflect what needs to be done.
