### ISSUE TITLE
Ampersands in text don't present correctly

### ISSUE THREAD

**Issue by Blueskies00** [openownership/visualisation-tool#123]
![Screenshot from 2022-08-18 09-43-13](https://user-images.githubusercontent.com/100690440/185351880-87dad420-38c1-4976-97b3-27683a05c634.png)

**Comment by paramjit74git** [comment]
We are facing this same issue. Was this bug ever looked at?

**Comment by kd-ods** [comment]
We haven't scheduled a development sprint for the visualisation tool since this bug was filed.

If you want to submit a pull request to address the bug, we will endeavour to review it in a timely fashion.

**Comment by codemacabre** [comment]
This is actually intended functionality by a `sanitise` function to reduce XSS attacks. However, the text is rendered inside SVG `text` nodes which D3<sup>1</sup> treats as `textContent`<sup>2</sup> which only renders text:

> no parsing is performed either, the input string is taken as pure textual content

Therefore, I think it's safe to remove the sanitisation of these `text` nodes.

***

[[1]](https://d3js.org/d3-selection/modifying#selection_text) D3 documentation
[[2]](https://www.w3.org/TR/DOM-Level-3-Core/core.html#Node3-textContent) W3C textContent specification

**Comment by StephenAbbott** [comment]
@paramjit74git Sorry for the delay - but work now done to fix this issue. 

@codemacabre will be fixing a few more things and then releasing an updated version of the visualisation tool very soon which I hope you can take advantage of
