### ISSUE TITLE
If possible, make `.label` selector used in line 230 of index.js less generic as it can find elements outside of the bods visualizer DOM nodes.

### ISSUE THREAD

**Issue by andrewShillito** [openownership/visualisation-tool#134]
https://github.com/openownership/visualisation-tool/blob/a6225e964d39ccedfb9acfa59764a2bafdb10740/src/index.js#L230

Background:
- The css selector here can unintentionally locate additional elements on the page which are not intended to be handled by bods-dagre.js.
- That can result in broken rendering for the visualizer as error can be thrown when those unexpected DOM nodes are located.

**Comment by andrewShillito** [comment]
@StephenAbbott Thank you! Sounds good.

**Comment by codemacabre** [comment]
I've increased the specificity to include the labels' parent classes, which will prevent unexpected `.label` elements being selected:
https://github.com/openownership/visualisation-tool/blob/e7c8cd7b262b8c389353ec015fe2d2dda1780c58/src/index.js#L230

**Comment by andrewShillito** [comment]
Looks good and thank you.
