### ISSUE TITLE
Bug: blank png downloaded alongside correct png each time 'Download PNG' is clicked

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/visualisation-tool#169]
During testing using the BODS Data Visualisation Demo version, I am experiencing a bug where the diagram is generated correctly - but when I click 'Download png', it downloads a blank file called bods.png and then a correct second png is downloaded called bods (1).png.

See example pngs generated using mixed-direct-and-indirect-ownership.json:
![Image](https://github.com/user-attachments/assets/b6a3846a-e1a2-424a-9944-d878fb7b56f3)
![Image](https://github.com/user-attachments/assets/acd3d42e-e169-4b8e-8ae3-d745afc9386c)

I carried out tests using the following two [BODS version 0.4 JSON example files](https://standard.openownership.org/en/0.4.0/examples/index.html): 
[mixed-direct-and-indirect-ownership.json](https://github.com/user-attachments/files/17380971/mixed-direct-and-indirect-ownership.json)
[fermcat (1).json](https://github.com/user-attachments/files/17380973/fermcat.1.json)

I'm on a MacBook Pro running 14.6.1 MacOS Sonoma using Chrome Version 129.0.6668.100 (Official Build) (arm64).

**Comment by kd-ods** [comment]
When I try to recreate this issue, what happens is that on clicking the 'Download PNG' button, two dialog boxes open (to save the image to my machine). I'm on Ubuntu 20, Firefox 131

**Comment by neelima-j** [comment]
I was able to recreate the bug as follows:
OS: MacOS Big Sur version 11.6, chip M1 2020
Browsers: Version 129.0.6668.100 (Official Build) (arm64) & Safari Version 14.1.2 (16611.3.10.1.6)

- First attempt to download the PNG, only one file is downloaded, as expected. 
- Without refreshing the page, if the same data is pasted, on clicking the 'Download PNG' button, 2 files are download as described in the issue. 
- Upon refreshing the page and repeating the steps, only one file is downloaded, as expected.

**Comment by StephenAbbott** [comment]
@kd-ods @codemacabre When using the [embedded BODS data visualiser](https://www.openownership.org/en/publications/beneficial-ownership-visualisation-system/bods-data-visualiser/) today, I experienced a bug similar to this previously documented exampled bug where eight blank png files were generated alongside the one correct png file when I clicked 'Download PNG'. 

I'm on a MacBook Pro running 14.6.1 MacOS Sonoma using Chrome Version 136.0.7103.93.

**Comment by kd-ods** [comment]
@StephenAbbott - thanks for reporting this. Can you supply the JSON file which is generating the issue?

**Comment by StephenAbbott** [comment]
@kd-ods I've just tested using the [tecido.json example file](https://github.com/openownership/data-standard/blob/0.4.0/examples/tecido.json) and that works fine in terms of generating only a single png file when you click Download PNG. 

But I experienced this issue when using the following example data, drawn from the [UK BODS version 0.4 dataset](https://bods-data.openownership.org/source/uk_version_0_4/):

[waterstones_example.json](https://github.com/user-attachments/files/20291321/waterstones_example.json)

The correct png file is generated but an additional blank png is downloaded along with two almost blank png files which seem to show the corner of one of the BOVS icons.
