### ISSUE TITLE
Operation of time slider handle

### ISSUE THREAD

**Issue by kd-ods** [openownership/visualisation-tool#180]
### Bug description

When the handle of the time slider is dragged to a new position, the user cannot drag it on to a further position without letting the handle go and then re-grabbing it.

### Steps to reproduce

1. Paste [this JSON](https://raw.githubusercontent.com/openownership/data-standard/refs/heads/example_drt_main/examples/fermcat.json) into the tool and click 'Draw'.
2. Click and hold down your mouse/pointing device to grab the time slider handle.
3. Drag the slider handle one step to the left, and maintain the grab action on the handle (keeping mouse button or equivalent pressed). 
4. Try to drag the handle one more step to the left. (You won't be able to.)
5. To drag the handle one more step to the left, release the handle and grab it again before moving it.

### Expected behaviour

Ideally the user would be able to drag the handle through multiple points on the time slider with a down-click -> move --> release action on their pointing device. (The diagram refreshing along the way.)

If this is too challenging to implement then some indication that the slider handle is no long under control would help the user.

**Comment by kd-ods** [comment]
@codemacabre - how much work would it be to address this?

**Comment by codemacabre** [comment]
@kd-ods I don't think it'd be too tricky. I think it's probably a case of adjusting the focus to remain on the slider during mouse events.

**Comment by kd-ods** [comment]
Thanks, Myles. I'll add it to the backlog.

**Comment by kd-ods** [comment]
Ah - you did that already! Thanks :-)
