### ISSUE TITLE
Mouse/pointer cursor on time slider handle could be more helpful to users

### ISSUE THREAD

**Issue by kd-ods** [openownership/visualisation-tool#181]
### Bug description

At the moment the standard pointer cursor is maintained throughout all interactions with the time slider handle. It would help users if clues were given for its operation.

### Steps to reproduce

1. Paste [this JSON](https://raw.githubusercontent.com/openownership/data-standard/refs/heads/example_drt_main/examples/fermcat.json) into the tool.
2. Drag your pointer to the time slider and along its length.

![Image](https://github.com/user-attachments/assets/f9c0c607-19ac-49f1-99c4-2d6d7ec8f6ce)

3. Click and drag the handle.

### Expected behaviour

On mousing over the slide handle, change cursor to pointing hand (as happens on clicking a node or edge in the main diagram).

On clicking and holding the slide handle, change cursor to grab hand.

On releasing the slide handle, cursor is pointing hand.

On mousing over the line element of the slider, the cursor is the standard arrow pointer and the slider is highlighted (as now.)

**Comment by codemacabre** [comment]
This is pretty trivial to fix; adding to the sprint.
