### ISSUE TITLE
Revisit whether SVG downloads and by necessity a 'pure' SVG diagram are required

### ISSUE THREAD

**Issue by stevenday** [openownership/visualisation-tool#25]
In the MVP process and particularly #8 we made a decision to use HTML inside a larger SVG diagram to get better presentation of nodes in a graph. This meant that directly downloading and editing a generated diagram in an SVG editor would be tricky. 

We removed the prototype code we had for this in 5f54d03, but acknowledged in #17 that it was worth checking back in on this decision in the future to see if we wanted to resurrect it. This ticket is a reminder of that.

**Comment by kd-ods** [comment]
> This meant that directly downloading and editing a generated diagram in an SVG editor would be tricky.

I'm just looking at some potential work where this feature would be very useful. FWIW
