### ISSUE TITLE
Option not to hide percentages / edge annotations

### ISSUE THREAD

**Issue by timgdavies** [openownership/visualisation-tool#36]
At the moment the graph hides edge annotations (e.g. percentages of ownership) when there are more than a particular number of nodes, or more than a given complexity. 

This is problematic for some use-cases. It would be useful to have:

(a) Option to toggle edges annotations on or off (even if starting state is determined by graph complexity)

and/or

(b) A default or optional layout algorithm that makes space for labels even in complex graphs.

(This comes from Louise's comment that:

>  I was looking to screenshot the Armenia ZCMC graph for a presentation i'm giving, to demonstrate the need to visualise complex declarations. Because there's no metadata on the graph edges it's not telling us things that would be useful to see at a glance (e.g. % ownership, also nature of OOC if that's captured in the declaration).)

**Comment by Lathrisk** [comment]
I have added a parameter that allows the control of the node label limit. The controls would need to added to the demo to be useful, and then instructions on how to implement in user applications. I think adding parameters to control the layout would also be fairly trivial, but we might want to do some testing to find out what would be useful in terms of layout options.

**Comment by kd-ods** [comment]
Closing on the basis that there is now a labelLimit parameter, documented in the [readMe](https://github.com/openownership/visualisation-tool?tab=readme-ov-file#installation--usage). And that #55 will look at how properties on nodes and edges can be made viewable.
