### ISSUE TITLE
Placeholder text in Paste textarea should be removed when textarea receives focus

### ISSUE THREAD

**Issue by jpmckinney** [openownership/visualisation-tool#49]
Otherwise, the user gets a confusing message about the JSON they pasted being invalid (typically, placeholder text doesn't stay in a given field).

**Comment by stevenday** [comment]
Fixed in https://github.com/openownership/openownership.beta/commit/3075970d6bb94d86948997517335bb241bf41334 by using a proper placeholder attribute. Thanks!
