### ISSUE TITLE
Tool erroneously treats interests array as required

### ISSUE THREAD

**Issue by kd-ods** [openownership/visualisation-tool#51]
If an ownership-or-control statement contains an empty interests array:

`"interests": []`

... then the diagram is drawn without problem. 

If the interests property is left out entirely no diagram is drawn and the error 'Sorry, there was an error drawing your data. Is it valid BODS?' pops us. (It is valid BODS, btw.)

**Comment by stevenday** [comment]
Thanks @kd-ods - this should be fixed now!
