### ISSUE TITLE
Add bar graphs to nodes with the total known ownership & control

### ISSUE THREAD

**Issue by stevenday** [openownership/visualisation-tool#6]
The following image is a concept for providing a detailed breakdown of how much of a particular entity's ownership is declared (i.e. known to us) vs undeclared:

<img width="475" alt="Screenshot 2020-03-30 at 21 18 36" src="https://user-images.githubusercontent.com/663700/77958023-55681200-72cc-11ea-9fde-b371cc1a2fad.png">

The general idea is that these graphs could be stacked bars (for different owners), with some empty space signifying how much is unknown/undeclared. They could also be presented as multiple bars:

<img width="904" alt="Screenshot 2020-03-30 at 21 21 35" src="https://user-images.githubusercontent.com/663700/77958171-8a746480-72cc-11ea-9c21-59950443e298.png">

For the purposes of this experiment, we'd like to explore how we could display *some kind* of bar around the node when the user has signalled an interest in a specific node. Thinking of touch compatibility, this would probably be via selecting the node on click/tap.

**Comment by Lathrisk** [comment]
Very Large: The best solution for this would be a popup or overlay as noted above. It will likely require a lot of D3 coding or additional graphing libraries, as well as some consideration for design, scale, layout, and functionality.

**Comment by StephenAbbott** [comment]
@kd-ods Yes, fine to close. We should focus efforts on https://github.com/openownership/visualisation-tool/issues/55 rather than this particular feature, based on user feedback
