### ISSUE TITLE
Create png (or similar) export option

### ISSUE THREAD

**Issue by kd-ods** [openownership/visualisation-tool#60]
This would be useful in all kinds of situations. At the moment, resizing the page, the diagram etc so that you can take a screenshot (which then needs to be cropped) is time-consuming and - more importantly - beyond some potential users of the tool.

**Comment by StephenAbbott** [comment]
As discussed, I've set up a project for visualisation sprint 3 in early 2022 and would be great if there is any time before sprint kicks off to investigate some of the high-priority issues around export functionality https://github.com/openownership/visualisation-tool/projects/2

**Comment by StephenAbbott** [comment]
@Lathrisk Wondering if we can learn from/reuse approaches laid out here https://github.com/jacomyal/sigma.js/issues/1150

**Comment by Lathrisk** [comment]
There is now a download option for SVG and PNG. It should be noted that the PNG option is pretty ropey. The resolution is low and the bounding area is fixed. We might want to look into options in future but at present the SVG download option should work.

**Comment by kd-ods** [comment]
@Lathrisk - you mentioned that you were trying to track down any documentation on deployment. Do you need to consolidate/update and document what 'deployment' means for the BODS visualiser as part of wrapping up this work and ticket?
