### ISSUE TITLE
Layout and style: convey direction of relationships

### ISSUE THREAD

**Issue by kd-ods** [openownership/visualisation-tool#71]
At the moment, it's often unclear:
a) whether company A owns/controls company B or the converse
b) which company (or potentially companies) is at the 'root' of a tree

For example, go to this [Armenian declaration](https://www.e-register.am/en/companies/1340197/declaration/c51e08a7-6fdb-4ab7-a55c-c74a68a8f54c) and use the 'Download as JSON' button (top right). The visualiser displays this data as:

![image](https://user-images.githubusercontent.com/35495305/133254109-e0813377-537b-463c-8334-25d6f0a6130b.png)

[BOVS](https://www.openownership.org/visualisation/core/directionality/) deals with directionality and clarity of the graph by: 

1) Using arrows
2) Layout-wise, essentially using columns or rows to order series of nodes

We need at least (1) and ideally (2), IMO.

**Comment by kd-ods** [comment]
(I've tagged this as a bug since it's currently possible to misunderstand data due to this issue.)

**Comment by Lathrisk** [comment]
Estimate: Small if the new SVG formatting permits easier edge positioning/termination, Medium if we need to manually calculate or redesign how we display directionality.

**Comment by Convincible** [comment]
Personally I think implement arrowheads by overlaying a single triangle at any connection point that has received a line.

**Comment by kd-ods** [comment]
This is how @Lathrisk 's work is looking so far:

![image](https://user-images.githubusercontent.com/35495305/154235107-3a160376-3f50-4277-ab2a-ce7550c3ca89.png)

"The arrowheads don't currently align perfectly with the edges, and where the line is thick we see the edge protrude from the sides of the arrowhead. I'm going to work on this a little more but good to know what the constraints/demands or on this and when to cut my losses."

> good to know what the constraints/demands or on this and when to cut my losses

My view on this is.... visual perfection in this tool is not necessary. (Nice, but not necessary.) So, but all means, see if some tweaking will neaten things up a bit, but it's not worth burning days of work on. (In the longer run, we might decide that super-slick visuals are worth the effort and devote 20 days of dev time remodelling the svg node output etc etc. But where we're at right now, is just making sure that information is accurately conveyed.)

@StephenAbbott - that sound ok to you?

@Lathrisk - you mentioned another ticket about the broadness of the edges? And its relevance to the arrow head look.

**Comment by Lathrisk** [comment]
@kd-ods @StephenAbbott Yes, there is a ticket in the backlog to look at line weight which will have an impact on these artefacts. For example if the maximum line weight is less than those shown here then the problem may never occur. I think this is something we can come back to, but I'm wary of sinking too much time into this now, especially if resolving other issues impacts this.

**Comment by Convincible** [comment]
Just my tuppence worth – I don't think it's important to get it to align perfectly. For instance you could even have the arrows terminating short of the node, if that's easier (see below). The only thing that's essential is just that it's clear which nodes are connected, and in which direction.

![image](https://user-images.githubusercontent.com/30758921/154248031-092df080-32be-4381-bdfc-c272fbc01336.png)

If text labels will overlay arrows, it would be better if they can be given a white background to aid reading the text.

**Comment by StephenAbbott** [comment]
We're in agreement, @kd-ods and @Convincible. The current implementation for arrowheads does enough to convey directionality which is the key aim here. Visual perfection is not necessary.
