### ISSUE TITLE
Scale BOVS diagram once Draw button on BOVS Visualiser is clicked so that entire diagram is visible

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/visualisation-tool#73]

**Comment by kd-ods** [comment]
@codemacabre - here are some BODS files to help with testing:

- [Example 1](https://drive.google.com/file/d/1LxkG2qt4icpO7tJ3luvYgo5czGKbLN09/view?pli=1)
- [Example 2](https://github.com/openownership/data-standard/blob/main/tests/data/bods-package/valid/valid-bods-package-fi-soe.json)
- [Example 3](https://drive.google.com/file/d/1-FMDjYBh4z9UyzmqvXf-8wTyZWhYEYFN/view?usp=drive_link)

Let me know if you need more.
