### ISSUE TITLE
Use the official BOVS icons

### ISSUE THREAD

**Issue by Convincible** [openownership/visualisation-tool#77]
Update visualiser to use the official icons: https://www.openownership.org/visualisation/core/vocabulary/

**Comment by Lathrisk** [comment]
Large: If I remember correctly this required downloading the SVG's and manually editing them in inkscape for use in the visualiser. I will also need to set up the code to parse the data and correctly handle each node type.

**Comment by StephenAbbott** [comment]
Thanks @Convincible. Will be in touch about this soon

**Comment by Lathrisk** [comment]
Thanks, @Convincible  

A quick note that I have used some of the default BOVS icons and they work out the box. I should be able to complete this issue without any additional assets but will update if I hit any that don't align correctly.

cc @StephenAbbott @kd-ods

**Comment by StephenAbbott** [comment]
That's great to hear, @Lathrisk. But do keep me and @Convincible posted in case you encounter any issues.

**Comment by StephenAbbott** [comment]
@Lathrisk Just want to check something with the comment above: the plan here is to follow the example I can see with [PLCs](https://github.com/openownership/visualisation-tool/pull/88/commits/df7b08972deb9fe1ed75801ef429f614fc07845e) and add in support for stateBody entity type ahead of BODS v0.3 changes in a few months, right? 

The [state](https://github.com/openownership/visualisation-tool/pull/88/commits/eab136ff01b44e8f9a7f093da0f723f6fbe7fe55#diff-1334c92a38e18a752dccae8c2277c5168b75b10602dc49d735dd650bc68c4789) and [unknown state](https://github.com/openownership/visualisation-tool/pull/88/commits/eab136ff01b44e8f9a7f093da0f723f6fbe7fe55#diff-ddef2942b257215d1f0fee7951a58a55467ee613c620edef3842c9d47368de11) svg icons are already in [current BOVS list](https://www.openownership.org/visualisation/core/vocabulary/) which I can see in the attached PR.

**Comment by Lathrisk** [comment]
Thanks, @StephenAbbott, I've updated the state and stateBody to use the state icons for now.

**Comment by StephenAbbott** [comment]
Great. Thanks @Lathrisk. @kd-ods and I are in a conversation with our designer Virgil about getting a stateBody icon very soon but just wanted to check this wasn't holding you up
