### ISSUE TITLE
Implement line weight representing interest strength

### ISSUE THREAD

**Issue by Convincible** [openownership/visualisation-tool#78]
![](https://d33wubrfki0l68.cloudfront.net/533f4c815458aee8fbedea7a815f5c1757e83a4b/f5451/visualisation/diagrams/bovs-optional-weight-calculation.png)

Implement 3-5 possible line weights that correspond to the strength of the interest represented by that line, where this information is given. Where it isn't given, the middle weight is used.

**Comment by Lathrisk** [comment]
Small: At present line weights are applied based on the strength of ownership or control but through an arbitrary scale. I'll look at the suggestions above and investigate these options.

**Comment by Convincible** [comment]
In recent visualisations I've taken a 3 or 5-grrade approach.

e.g. there are only 5 line weights available, no.3 is a "normal" weight, then there are 2 lighter weights for e.g. <25% and 50%, and 2 heavier weights.

**Comment by Lathrisk** [comment]
@kd-ods @StephenAbbott @Convincible 

For note, at present the tool has a 10 point system in which the line weight is either:

`exact / 10`

or 

`(minimum + maximum / 2) / 10`

It would be good to know if we definitely want to move away from that towards a reduced 3 or 5 point system as suggested in this ticket.

**Comment by StephenAbbott** [comment]
Great to hear your thoughts on this question from @Lathrisk, @Convincible ☝️

**Comment by Convincible** [comment]
It's important that the default line has a sensible readable thickness. This is the line that should be used at the midpoint (50% interest), when interest strength is unknown, or if variable line width is disabled.

So we work backwards from here: decide the most comfortable line width for a "normal" line, then show a lighter line when interest is known to be less strong, or a heavier line when it is known to be stronger. 

Something like:

``` javascript
// interestStrength: strength represented as a number between 0 and 1

const defaultLine = 2; // pixels/units, for example
const minLine = 1; // minimum line width, for example

lineThickness = ( interestStrength * 2 * (defaultLine - minLine) ) + minLine;
// multiply by 2 centres the range of thicknesses around the defaultLine thickness

// interestStrength = 0.01 will return minLine thickness
// interestStrength = 0.5 will return defaultLine thickness
// interestStrength = 1 will return defaultLine thickness plus the difference between min/default
```

**Comment by kd-ods** [comment]
Noting that when we have data where a 0% interest is specified, no line is displayed at all (which is fine, I think), but the arrow-head still appears.

```
        "interests": [
            {
                "type": "shareholding",
                "interestLevel": "direct",
                "beneficialOwnershipOrControl": false,
                "share": {
                    "exact": 0
                }
            }
        ]
```

**Comment by Lathrisk** [comment]
@kd-ods perhap we should draw the minimum line value when this occurs so that some sort of relationship is conveyed? (cc @lgs85)

**Comment by kd-ods** [comment]
> perhaps we should draw the minimum line thickness when this occurs so that some sort of relationship is conveyed?

@Lathrisk - the thing is, there are better ways in BODS 0.3 to represent a relationship about which there is no information. We do, though, need to work out the precise circumstances under which:

- no line is drawn
- a minimal line is drawn
- a line is given some weight

I need to think about this a bit.

In the meantime can you let me know how the code handles multiple interests in the array? That is: how is line styling and weight determined at the moment in those cases?

**Comment by kd-ods** [comment]
My current thinking on this is that - for the moment- this should the how the visualiser renders edges:

- no line is drawn
  - when the `interests` property doesn't exist in an ooc statement
  - when the `interests` value is an empty array 
  - when there is a single interest in the array and share.exact == 0  (maximum & minimum are both 0)
- a minimal line is drawn
  - in all other cases, although...
- a line is given some weight
  - when interest.type is 'voting-rights' or 'shareholding' and the share value is not 0.

**Comment by lgs85** [comment]
@Lathrisk @kd-ods thanks for flagging. This ultimately comes down to the discussion of to what extent we want to use the tool to highlight deficiencies in BODS data vs being forgiving of them. Despite the problems with it, I also lean towards drawing a line in the cases of missing/empty interests arrays, not least because i) AFAICS the interests array isn't listed as required in the BODS schema, and ii) in practise this will result in a lot of the public data being shown as visualisations consisting solely of floating nodes. I think that no line is probably fine in instances where only a 0% shareholding interest is provided, but think we'd need to clearly document this behaviour so it doesn't get mistaken for a bug

**Comment by kd-ods** [comment]
@Lathrisk and I agreed to go ahead with a plain black line in all 3 cases, for simplicity's sake.
