### ISSUE TITLE
Minimal set of BODS features & properties required for a diagram to be rendered

### ISSUE THREAD

**Issue by kd-ods** [openownership/visualisation-tool#81]
BODS doesn't need to be valid to be interpreted and rendered as a diagram by the visualiser.

There will be a minimal set of BODS features & properties required to make a diagram 'renderable', though. It should be made clear to users what that set is. 

(As new visual features are added to the visualiser which are dependent on BODS data, it should be considered whether the related BODS property is added to the minimal set.)

**Comment by kd-ods** [comment]
I'm going to stash things on this issue which may relate to this work. 

atm an image won't render if the BODS version (publicationDetails.bodsVersion) isn't the same for all statements in a BODS array.

**Comment by StephenAbbott** [comment]
@kd-ods @Lathrisk Dealing with this issue and https://github.com/openownership/visualisation-tool/issues/70 didn't make it into sprint 4 release, right? Let's discuss tomorrow

**Comment by lgs85** [comment]
@StephenAbbott - @Lathrisk put [this](https://github.com/openownership/visualisation-tool/blob/master/docs/spec.md) together, which goes some way to achieving this (cc @kd-ods)

**Comment by StephenAbbott** [comment]
Link now added to readme so closing issue
